server:
    applicationConnectors:
      - type: http
        port: 8085

viewRendererConfiguration:
  .ftl:
    strict_syntax: yes
    whitespace_stripping: yes

WebViews: 
    - className: org.gradiant.fgttrainer.views.Index
